#!/bin/bash

for i in $(find src/ -type d);
  do
  count=`ls -1 $i/*.java 2>/dev/null | wc -l`
  if [ $count != 0 ]; then echo; fi
  echo "$count JAVA files found in $i:"

  if [ $count != 0 ]
  then
    ls -1 $i/*.java

    echo
    javac -g -cp src/ $i/*.java

    # bin/ counterpart
    bdir="bin/${i:4}"

    if [ ! -d $bdir ]
    then mkdir -p $bdir
    fi

    set -x
    mv -fv  $i/*.class "$bdir"
    { set +x; } 2>/dev/null
  fi
done;

# This is extremely peculiar but it must be done: if you can find a solution please fix it
rm src/com/idt/contest/highschool/winter2014/framework/FrameworkConstants.class
